### ISSUE TITLE
Create Latching Mode for current_state topics

### ISSUE THREAD

**Issue by adnanmunawar** [jhu-cisst/cisst-ros#5]
https://github.com/jhu-cisst/cisst-ros/blob/a6ced7f24a630c5d7513b7303a67ae8276f069ef/cisst_ros_bridge/include/cisst_ros_bridge/mtsROSBridge.h#L62

For state topics, we should use latching mode enabled.
Use Case:
Lets say the robot is already up and running and has been homed already,  we now run the user application in ROS. In the user application if we subscribe to topic <namespace>/current_state, we wouldn't know what state is in as this topic is active only when the state changes. Having latched information would be helpful in case we want to know what the last state was.

**Comment by adeguet1** [comment]
That totally makes sense.  I can add this feature pretty quickly.   Any thoughts/experience for the queue size?  It seems that for most cases we tend to "stream" data so a queue is not really needed for our publishers.   I honestly can't recall why we have a default set to 5.

**Comment by adnanmunawar** [comment]
I agree, the queue size for latched data doesn't make much sense, we could leave it at 5 or just set it to 1. In your plan for implementation, would you prefer a new class for topics that stream strings/status or just add a condition for this specific topic.

Personally I was thinking of a new class, something like
**mtsROSEventStatusWritePublisher: public mtsROSPublisherBase**
 just like we have one for
**class mtsROSEventWritePublisher: public mtsROSPublisherBase**
and set the latching explicitly for this type of class. But I could be jumping the gun.

Regarding the queue size default of 5;
Although I am just guessing, many examples of publishers on the Internet use a default of 5 (which might have come from the default queue limit of **5** for the accept function for old sockets), so could be "Old habits die hard"

**Comment by adeguet1** [comment]
I modified all mtsROSPublishers constructors to allow setting queue size and latch.   The main difference is that when I used AddPublisherFromEvent, the default queue size is 1 and latch is true.   for publishers From commands, since these are mostly periodic publish (stream), I assumed latch should be false by default and I kept the previous default of 5 for the queue size (no good reason here, jus trying to not change current behavior).  See 624044efa022bc7a4ecce1397aafa0aeefc6f100.   @adnanmunawar , can you pull the devel for cisst-ros and see if this works?

**Comment by adeguet1** [comment]
Tested and fixed issue when topic was latched but wrapper was skipping ros::publish because there were no subscribers (see eda396515714f5abf375a34f98b0023972d4697a)
